version: '2.1'

volumes:
  settings:
  pihole_config:
  dnsmasq_config:

services:
  # https://github.com/balenablocks/fbcp
  fbcp:
    image: balenablocks/fbcp:1.0.0
    privileged: true

  # balena-dash
  kiosk:
    restart: always
    build: ./balena-dash/kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/data'
    environment:
      - KIOSK=1
  scheduler:
    restart: always
    build: ./balena-dash/scheduler
    privileged: true
    environment:
      - ENABLE_BACKLIGHT_TIMER=1
      - BACKLIGHT_ON=0 9 * * *
      - BACKLIGHT_OFF=0 20 * * *
      - TZ=America/Los_Angeles
  wifi-connect:
    build: ./balena-dash/wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'

  # balena-pihole
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    labels:
      io.balena.features.supervisor-api: 1
  # https://github.com/klutchell/unbound-dnscrypt
  unbound:
    build: ./balena-pihole/unbound
    privileged: true
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
  # prevent plymouth from blocking fbcp
  # https://github.com/klutchell/balena-pihole/issues/25
  # https://github.com/balena-os/meta-balena/issues/1772
  dbus:
    build: ./balena-pihole/dbus
    restart: on-failure
    labels:
        io.balena.features.dbus: "1"
